apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: url-shortener
  labels:
    app: frontend
    tier: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shortener-sa
  namespace: url-shortener
  labels:
    app: shortener
    tier: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-sa
  namespace: url-shortener
  labels:
    app: analytics
    tier: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: url-shortener
  labels:
    app: postgres
    tier: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra-sa
  namespace: url-shortener
  labels:
    app: cassandra
    tier: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-sa
  namespace: url-shortener
  labels:
    app: nats
    tier: messaging 