apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: url-shortener
  labels:
    app: nats
    tier: messaging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
        tier: messaging
    spec:
      serviceAccountName: nats-sa
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                - nats
              topologyKey: kubernetes.io/hostname
          - weight: 80
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                - nats
              topologyKey: topology.kubernetes.io/zone
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 70
            preference:
              matchExpressions:
              - key: network-latency
                operator: In
                values:
                - low
                - ultra-low
          - weight: 50
            preference:
              matchExpressions:
              - key: node-performance
                operator: In
                values:
                - high
                - premium
          - weight: 30
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
      containers:
      - name: nats
        image: nats:2.9-alpine
        ports:
        - containerPort: 4222
        - containerPort: 8222
        command:
        - nats-server
        - --jetstream
        - --cluster_name=urlshortener-cluster
        - --cluster=nats://0.0.0.0:6222
        - --routes=nats://nats-1.url-shortener.svc.cluster.local:6222,nats://nats-2.url-shortener.svc.cluster.local:6222
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m" 