apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: analytics-role-binding
  namespace: url-shortener
  labels:
    app: analytics
    tier: backend
subjects:
- kind: ServiceAccount
  name: analytics-sa
  namespace: url-shortener
roleRef:
  kind: Role
  name: analytics-role
  apiGroup: rbac.authorization.k8s.io