apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-role-binding
  namespace: url-shortener
  labels:
    app: frontend
    tier: frontend
subjects:
- kind: ServiceAccount
  name: frontend-sa
  namespace: url-shortener
roleRef:
  kind: Role
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io