apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-role-binding
  namespace: url-shortener
  labels:
    app: postgres
    tier: database
subjects:
- kind: ServiceAccount
  name: postgres-sa
  namespace: url-shortener
roleRef:
  kind: Role
  name: database-role
  apiGroup: rbac.authorization.k8s.io