apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: url-shortener
  labels:
    app: cassandra
spec:
  ports:
  - port: 9042
    name: cql
  clusterIP: None # It's required to create a Headless Service
  selector:
    app: cassandra