apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
  namespace: url-shortener
spec:
  accessModes:
    - ReadWriteOnce # Read-Write by only a single node
  resources:
    requests:
      storage: 10Gi