apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: url-shortener
  labels:
    app: nats
spec:
  ports:
  - port: 4222
    targetPort: 4222
    name: client
  - port: 8222
    targetPort: 8222
    name: http
  selector:
    app: nats