apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shortener-custom-hpa
  namespace: url-shortener
  labels:
    app: shortener
    tier: backend
    type: custom-metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shortener
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  - type: Object
    object:
      metric:
        name: url-creation-rate
      describedObject:
        apiVersion: v1
        kind: Service
        name: shortener-service
      target:
        type: AverageValue
        averageValue: 50
  - type: Object
    object:
      metric:
        name: database-connection-pool-usage
      describedObject:
        apiVersion: v1
        kind: Service
        name: shortener-service
      target:
        type: AverageValue
        averageValue: 80