apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: url-shortener
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  selector:
    app: frontend 