apiVersion: v1
kind: Service
metadata:
  name: shortener
  namespace: url-shortener
  labels:
    app: shortener
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: shortener