apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: url-shortener
  labels:
    app: analytics
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  selector:
    app: analytics